version: '3.8'

services:
  marzban-panel:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - marzban_data:/var/lib/marzban
      - ./automated-certs/ca:/etc/marzban/ca:ro                    # CA certificates
      - ./automated-certs/panel:/etc/marzban/panel-certs:ro        # Panel client certificates
      - ./xray_config/config.json:/etc/marzban/xray_config/config.json:ro
    environment:
      - UVICORN_SSL_CA_TYPE=private
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - DATABASE_URL=sqlite:////var/lib/marzban/db.sqlite3
      - AUTOMATED_CERTIFICATES=true
    networks:
      - marzban_network
    depends_on:
      - marzban-db-migration

  marzban-db-migration:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    volumes:
      - marzban_data:/var/lib/marzban
    environment:
      - DATABASE_URL=sqlite:////var/lib/marzban/db.sqlite3
    command: ["alembic", "upgrade", "head"]
    networks:
      - marzban_network

  # Certificate management service
  marzban-cert-manager:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    volumes:
      - marzban_data:/var/lib/marzban
      - ./automated-certs:/app/automated-certs
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=sqlite:////var/lib/marzban/db.sqlite3
    command: ["python", "/app/scripts/certificate-daemon.py"]
    networks:
      - marzban_network
    depends_on:
      - marzban-db-migration

networks:
  marzban_network:
    driver: bridge

volumes:
  marzban_data:
