services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./certs:/var/lib/marzban/certs:ro
