"""add client key store

Revision ID: 622a8ec95acb
Revises: d39d601569db
Create Date: 2025-05-31 21:41:22.865629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622a8ec95acb'
down_revision = 'd39d601569db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('panel_client_cert_pem', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('panel_client_key_pem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'panel_client_key_pem')
    op.drop_column('nodes', 'panel_client_cert_pem')
    # ### end Alembic commands ###
