"""add_active_node_to_user_and_node_to_proxyhost

Revision ID: d39d601569db
Revises: 52127ce5be0c
Create Date: 2025-05-31 10:39:39.348482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39d601569db'
down_revision = '52127ce5be0c'
branch_labels = None
depends_on = None



def upgrade():
    # Clean up any leftover temporary tables
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_hosts")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_users")

    # Drop existing indexes if they exist
    op.execute("DROP INDEX IF EXISTS ix_hosts_node_id")
    op.execute("DROP INDEX IF EXISTS ix_users_active_node_id")

    # tables removed once, so guard them
    for t in ("user_node_selections", "exclude_inbounds_association"):
        op.drop_table(t, if_exists=True)

    with op.batch_alter_table("hosts", recreate="always") as b:
        b.add_column(sa.Column("node_id", sa.Integer()))
        b.create_index("ix_hosts_node_id", ["node_id"], unique=False)
        b.create_foreign_key("fk_proxy_host_node", "nodes",
                             ["node_id"], ["id"])

    with op.batch_alter_table("users", recreate="always") as b:
        b.add_column(sa.Column("active_node_id", sa.Integer()))
        b.create_index("ix_users_active_node_id", ["active_node_id"],
                       unique=False)
        b.create_foreign_key("fk_user_active_node", "nodes",
                             ["active_node_id"], ["id"])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_active_node', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_node_id'), table_name='users')
    op.drop_column('users', 'active_node_id')
    op.drop_constraint('fk_proxy_host_node', 'hosts', type_='foreignkey')
    op.drop_index(op.f('ix_hosts_node_id'), table_name='hosts')
    op.drop_column('hosts', 'node_id')
    op.create_table('exclude_inbounds_association',
    sa.Column('proxy_id', sa.INTEGER(), nullable=True),
    sa.Column('inbound_tag', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['inbound_tag'], ['inbounds.tag'], ),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], )
    )
    op.create_table('user_node_selections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('node_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###
