"""move to account_numbers

Revision ID: e7a5f54960a1
Revises: 30ba9784801b
Create Date: 2025-05-29 13:50:52.885000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a5f54960a1'
down_revision = '30ba9784801b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_number', sa.String(length=36), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_account_number'), 'users', ['account_number'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=34), nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=128), nullable=True))
    op.drop_index(op.f('ix_users_account_number'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'account_number')
    # ### end Alembic commands ###
